### PR TITLE
tr: Add qtbase translation file

### PR DESCRIPTION
**Pull request by nowhszh**
qtbase_xxx.qm is the  basic translation file provided by QT.
here is the comparison after modification. The left side is master, the right side is this PR.
image

### CODE REVIEW

**Comment by variar** [comment]
It is indeed better with added Qt translations. However, I expect those qm files to be different it major Qt releases. I think I saw a cmake function that adds Qt translations from Qt version used during compilation. I'll search for it again.

**Comment by nowhszh** [comment]
> It is indeed better with added Qt translations. However, I expect those qm files to be different it major Qt releases. I think I saw a cmake function that adds Qt translations from Qt version used during compilation. I'll search for it again.

It may be possible to use a different version of the ts file, available from the repository [https://code.qt.io/cgit/qt/qttranslations.git](https://code.qt.io/cgit/qt/qttranslations.git). Then select them at compile time.

**Comment by nowhszh** [comment]
`src/app/i18n/qtbase/6/qtbase_zh_CN.ts` from [https://github.com/qt/qttranslations/tree/6.4.3/translations](https://github.com/qt/qttranslations/tree/6.4.3/translations).
`src/app/i18n/qtbase/5/qtbase_zh_CN.ts` from [https://github.com/qt/qttranslations/tree/5.15/translations](https://github.com/qt/qttranslations/tree/5.15/translations).
[qttranslations](https://github.com/qt/qttranslations) does not provide ts files for the English language, because the application is in English by default, so I created two empty files.

**Comment by variar** [comment]
I've pushed a change that collects Qt translations from Qt version that is used during build.

**Pull request closed without merging**
