### PR TITLE
Add context menu item to search with the current selection 

### PR DESCRIPTION
**Pull request by danberindei**

### CODE REVIEW

**Comment by variar** [comment]
Thanks! Looks good. CI build errors are because I've switched to more concise log macro. If rebasing on top of recent version is too hard I can manually merge this.

**Comment by danberindei** [comment]
@variar I can make the changes myself, but I can't build locally because of

```
$ cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
$ cmake --build .
...
[ 63%] Building CXX object 3rdparty/hyperscan/util/CMakeFiles/expressionutil.dir/expressions.cpp.o
/home/dan/Work/klogg/3rdparty/hyperscan/util/expressions.cpp:29:10: fatal error: config.h: No such file or directory
   29 | #include "config.h"
      |          ^~~~~~~~~~
```

**Comment by danberindei** [comment]
I realize now I was also wrong to allow add/replace to search in non-regex mode.

Replace makes sense for fixed strings, but the implementation escapes the string assuming regex so it's not really useful.

**Comment by variar** [comment]
Looks like `cmake --build .` tries to build some additional hyperscan utilities. I'll try to remove them.
Meanwhile building with `cmake --build . -t klogg_portable` should work

**Comment by variar** [comment]
Escaping is a bit tricky. "Add to search" should work only for regex mode and escape input strings. And "Replace search" may work in both modes, but escape strings only when regex mode is selected.

**Comment by variar** [comment]
`--build .` should be fixed in 7440d6a

**Comment by danberindei** [comment]
Thanks Anton, it worked, and I finally noticed that VS Code automatically inserted a `}` for me when I typed `{` :)

**Comment by variar** [comment]
@danberindei I've decided to allow "add to search" in non-regex mode and refactored a bit around that in 198f7eb

**Comment by danberindei** [comment]
Nice!

**Pull request merged**
