### PR TITLE
Add a feature to keep current search and show a new search results in a new tab (#576)

### PR DESCRIPTION
**Pull request by Abay11**
image
@variar, there is still some bugs, but I would to know what do think? Could we accept this?

### CODE REVIEW

**Comment by variar** [comment]
Thats a big feature! I'll go through the changes later this week.

**Comment by czlitony** [comment]
I like this feature!

**Comment by Abay11** [comment]
Thank you. There is still a few bugs. I'm working on it

**Comment by Abay11** [comment]
I've just pushed a new commit. Now this feature looks like working properly.
GIF 6-18-2023 8-40-20 AM

But I want to point out your attention at the line 383 src/ui/src/crawlerwidget.cpp. As I understand for proper work for each tab with results we need to create its own instance of LogFilteredData.
I'm not sure this is correct to do so. As far as I understand architecturally it is expected to have only one instance of LogFilteredData per an opened file, because an instance of LogFilteredData is passed in the LogFilteredData contructor. I am afraid creating new instances of this class internally in the CrawlerWidget may lead to some unexpected behavior.
@variar, could you please give me some tips how to properly implement this feature?

**Comment by variar** [comment]
LogFilteredData is using passed logData as a source of string information. Should be fine to have multiple of those. Not sure how the things will work if two searches are done in parallel on the same LogData.

**Comment by Abay11** [comment]
I've added interrupting a search if a user started a new search in the new tab or switches between tabs.
Open this PR. Please if you think something wrong let me know, I will try to find another solution

**Comment by variar** [comment]
Great work! I expected this to be more involved, but your implementation is nice and clean.

**Pull request merged**
