### PR TITLE
Add i18n for Klogg

### PR DESCRIPTION
**Pull request by nowhszh**
Newly added support for Chinese language, the translation part is not finished yet

### CODE REVIEW

**Comment by Junbo-Zheng** [comment]
> Newly added support for Chinese language, the translation part is not finished yet

@nowhszh Can you please add some screenshots of support for the Chinese language?

**Comment by nowhszh** [comment]
zh
@Junbo-Zheng like this.

**Comment by nowhszh** [comment]
@variar  Can you help me to explain the meaning of "include into cycle" in the color lable of Highlight configure?I don't know how to translate it.

**Comment by variar** [comment]
> @variar  Can you help me to explain the meaning of "include into cycle" in the color lable of Highlight configure?I don't know how to translate it.

There is a shortcut that applies the next color label to selected text. Only lables with "include into cycle" enabled are used in this sequence. It is useful to quickly mark text with 2-3 different colors instead of going through all configured colors.

**Comment by nowhszh** [comment]
> > @variar  Can you help me to explain the meaning of "include into cycle" in the color lable of Highlight configure?I don't know how to translate it.
> 
> There is a shortcut that applies the next color label to selected text. Only lables with "include into cycle" enabled are used in this sequence. It is useful to quickly mark text with 2-3 different colors instead of going through all configured colors.

Thanks, I understand.

**Pull request closed without merging**
