### PR TITLE
feat: Add some shortcut

### PR DESCRIPTION
**Pull request by nowhszh**
- To make it easier to add shortcuts without missing parameters, change the default storage structure for shortcuts
- Add new shortcut options: full screen, maximise/smallen window, preferences

### CODE REVIEW

**Comment by variar** [comment]
This is a useful change. Any chance you could rebase it on top of recent master?

**Comment by nowhszh** [comment]
> This is a useful change. Any chance you could rebase it on top of recent master?

Sure. I'll rebase it later.

**Comment by nowhszh** [comment]
> This is a useful change. Any chance you could rebase it on top of recent master?

done

**Comment by nowhszh** [comment]
This PR seems to have been forgotten

**Pull request merged**
